### ISSUE TITLE
Link to Unix Cheat Sheet broken

### ISSUE THREAD

**Issue by savannahmhunter** [ucdavisdatalab/workshop_introduction_to_the_command_line#3]
Link in reader to "Unix Cheat Sheet" is broken. Here is [the link](http://www.mathcs.emory.edu/~valerie/courses/fall10/155/resources/unix_cheatsheet.html) from the reader.

**Comment by t-shoemaker** [comment]
Thanks for catching this! We've moved the cheat sheet to a local file.
